import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
term = "xterm-256color"

[font.normal]
family = "JetBrainsMono Nerd Font"
# family = "Fira Code NerdFont"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"
